services:
  - name: redis
    type: web
    env: {}
    plan: starter
    image: 'redis:alpine'
    startCommand: ["redis-server"]

  - name: mongodb
    type: web
    env:
      - PUID=1000
      - PGID=1000
    plan: starter
    image: mongo
    startCommand: ["mongod", "--bind_ip_all"]
    ports:
      - 27017

  - name: api
    type: web
    env:
      - NODE_ENV=${NODE_ENV}
      - API_ROOT_URL=${API_ROOT_URL}
      # Adicione aqui outras variáveis de ambiente necessárias para o serviço API
    plan: starter
    image: 'ghcr.io/novuhq/novu/api:0.21.0'
    startCommand: ["npm", "start"]
    ports:
      - 3000
    dependsOn:
      - mongodb
      - redis

  - name: worker
    type: web
    env:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
      # Adicione aqui outras variáveis de ambiente necessárias para o serviço Worker
    plan: starter
    image: 'ghcr.io/novuhq/novu/worker:0.21.0'
    startCommand: ["npm", "start"]
    dependsOn:
      - mongodb
      - redis

  - name: ws
    type: web
    env:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URL=${MONGO_URL}
      # Adicione aqui outras variáveis de ambiente necessárias para o serviço WS
    plan: starter
    image: 'ghcr.io/novuhq/novu/ws:0.21.0'
    startCommand: ["npm", "start"]
    dependsOn:
      - mongodb
      - redis

  - name: web
    type: web
    env:
      - NODE_ENV=${NODE_ENV}
      - API_ROOT_URL=${API_ROOT_URL}
      # Adicione aqui outras variáveis de ambiente necessárias para o serviço Web
    plan: starter
    image: 'ghcr.io/novuhq/novu/web:0.21.0'
    startCommand: ["npm", "start"]
    dependsOn:
      - api
      - worker

  - name: widget
    type: web
    env:
      - NODE_ENV=${NODE_ENV}
      - API_ROOT_URL=${API_ROOT_URL}
      # Adicione aqui outras variáveis de ambiente necessárias para o serviço Widget
    plan: starter
    image: 'ghcr.io/novuhq/novu/widget:0.21.0'
    startCommand: ["npm", "start"]
    dependsOn:
      - api
      - worker
      - web

  - name: embed
    type: web
    env:
      - WIDGET_URL=${WIDGET_URL}
      # Adicione aqui outras variáveis de ambiente necessárias para o serviço Embed
    plan: starter
    image: 'ghcr.io/novuhq/novu/embed:0.21.0'
    startCommand: ["npm", "start"]
    dependsOn:
      - widget
