services:
  - type: web
    name: redis
    runtime: docker
    image: 'redis:alpine'
    envVars: []
    plan: starter
    startCommand: ["redis-server"]

  - type: web
    name: mongodb
    runtime: docker
    image: mongo
    envVars:
      - key: PUID
        value: "1000"
      - key: PGID
        value: "1000"
    plan: starter
    startCommand: ["mongod", "--bind_ip_all"]
    ports: [27017]

  - type: web
    name: api
    runtime: docker
    image: 'ghcr.io/novuhq/novu/api:0.21.0'
    envVars:
      - key: NODE_ENV
        value: ${NODE_ENV}
      - key: API_ROOT_URL
        value: ${API_ROOT_URL}
      # Adicione outras variáveis de ambiente conforme necessário para o serviço API
    plan: starter
    startCommand: ["npm", "start"]
    ports: [3000]
    dependsOn:
      - redis
      - mongodb

  - type: web
    name: worker
    runtime: docker
    image: 'ghcr.io/novuhq/novu/worker:0.21.0'
    envVars:
      - key: NODE_ENV
        value: ${NODE_ENV}
      - key: MONGO_URL
        value: ${MONGO_URL}
      # Adicione outras variáveis de ambiente conforme necessário para o serviço Worker
    plan: starter
    startCommand: ["npm", "start"]
    dependsOn:
      - redis
      - mongodb

  - type: web
    name: ws
    runtime: docker
    image: 'ghcr.io/novuhq/novu/ws:0.21.0'
    envVars:
      - key: NODE_ENV
        value: ${NODE_ENV}
      - key: MONGO_URL
        value: ${MONGO_URL}
      # Adicione outras variáveis de ambiente conforme necessário para o serviço WS
    plan: starter
    startCommand: ["npm", "start"]
    dependsOn:
      - redis
      - mongodb

  - type: web
    name: web
    runtime: docker
    image: 'ghcr.io/novuhq/novu/web:0.21.0'
    envVars:
      - key: NODE_ENV
        value: ${NODE_ENV}
      - key: API_ROOT_URL
        value: ${API_ROOT_URL}
      # Adicione outras variáveis de ambiente conforme necessário para o serviço Web
    plan: starter
    startCommand: ["npm", "start"]
    dependsOn:
      - api
      - worker

  - type: web
    name: widget
    runtime: docker
    image: 'ghcr.io/novuhq/novu/widget:0.21.0'
    envVars:
      - key: NODE_ENV
        value: ${NODE_ENV}
      - key: API_ROOT_URL
        value: ${API_ROOT_URL}
      # Adicione outras variáveis de ambiente conforme necessário para o serviço Widget
    plan: starter
    startCommand: ["npm", "start"]
    dependsOn:
      - api
      - worker
      - web

  - type: web
    name: embed
    runtime: docker
    image: 'ghcr.io/novuhq/novu/embed:0.21.0'
    envVars:
      - key: WIDGET_URL
        value: ${WIDGET_URL}
      # Adicione outras variáveis de ambiente conforme necessário para o serviço Embed
    plan: starter
    startCommand: ["npm", "start"]
    dependsOn:
      - widget

databases:
  - name: mongodb
    ipAllowList: []
    # Adicione outras configurações específicas do banco de dados conforme necessário

envVarGroups:
  # Adicione grupos de variáveis de ambiente se necessário para a aplicação

